spring.application.name=matching-engine

spring.datasource.url=jdbc:postgresql://localhost:5432/matching_engine
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=3000

spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=8080

logging.level.com.trading.matching_engine=DEBUG
